import Link from "next/link";
import {
  WebContent,
  Heading,
  NamedList,
  Entry,
} from "@/components/documents/Page";

export default function HomePage() {
  return (
    <WebContent
      name="Multi-Layer Acoustic Model"
      text="Demonstration Web Application by Dr Alexander Cave"
      numPages={1}
      pageNum={1}
    >
      <Heading text="Objective">
        <p>
          The multi-layer web application is a demonstration of{" "}
          <Link
            className="text-blue-700 hover:underline"
            href="/Levesque_Piche_1992.pdf"
          >
            D. Levesque and L. Piche acoustic physics model
          </Link>
          . It models plane wave at some angle of incidence being reflected
          (Rp,Rs) off and traveling through (Tp, Ts) multiple layers of possibly
          resonant material. The coefficients are generated as complex numbers
          representing the amplitude and phase of reflected compression (Rp) and
          reflected shear (Rs) waves as well as transmitted compression (Tp) and
          transmitted shear (Ts) waves.
        </p>
        <p>
          The layers are made of fluids and or solids where the distinction is
          made that a fluid material layer cannot support shear waves. The
          layers are surrounded on either side by possibly dissimilar mediums
          where the first and final layers do not have layer thickness. The
          incident wave can be a compressional or shear wave provided the first
          layer can support a shear wave and this incident wave has both and
          angle of incidence and a frequency. Plots are generated by the web
          application where either the incident wave frequency or angle is swept
          and defines the x-axis of the figures.
        </p>
        <p>
          The material properties as defined through data specifying the
          density, compressional wave speed (m/s) and attenuation (db/m) or the
          compressional modulus as well as for solids the shear wave speed (m/s)
          and attenuation (db/m) or the shear modulus. The models are defined
          through specifying the materials of the first, finial and intermediate
          layers. Where the intermediate layers further defined through layer
          thickness.
        </p>
      </Heading>

      <Heading text="Web Application Functional Description">
        <p></p>
      </Heading>

      <Heading text="Full-Stack Technologies">
        <NamedList name="Programming Languages:">
          <li>C++, C, C#, Python, Fortran, JavaScript</li>
        </NamedList>
        <NamedList name="Web Development:">
          <li>HTML, CSS, React.js, Node.js, Django, REST APIs</li>
        </NamedList>
        <NamedList name="Embedded Development:">
          <li>Cross-compiling with GNU, Bare-metal Programming</li>
          <li>
            Linux Device Drivers, Real-Time Operating Systems (RTOS), Debian
            Builds
          </li>
        </NamedList>
        <NamedList name="Tools and Platforms:">
          <li>Git, Docker, Linux, AWS, Azure, CI/CD (GitHub Actions)</li>
        </NamedList>
        <NamedList name="Software Development and Methodologies:">
          <li>Object-Oriented Programming (OOP), Functional Programming</li>
          <li>Agile, Scrum, Waterfall, Test-Driven Development (TDD)</li>
        </NamedList>
        <NamedList name="Other Technologies and Interests:">
          <li>
            Embedded Systems, IoT, Robotics, Machine Learning, Data Science
          </li>
          <li>
            PCB Design, Circuit Prototyping, Microcontrollers (STM32), Raspberry
            Pi
          </li>
          <li>3D Printing and CAD (Autodesk Inventor)</li>
        </NamedList>
      </Heading>
      <Heading text="Work Experience:">
        <Entry
          title="Python Developer"
          leftText="Tohen Holdings"
          rightText="March 2022-Present"
        >
          <p>
            Designed and optimised algorithmic trading systems for a fintech
            startup, improving backtesting efficiency and execution latency.
            Designed and optimized trading strategies, API consumption, data
            management, and reporting in Python, leveraging scientific libraries
            for analytics and performance tuning.
          </p>
        </Entry>

        <Entry
          title="Backend C++ Developer"
          leftText="Industrial Science Group"
          rightText="March 2021 - March 2022"
        >
          <p>
            Developed C++ backend code as a subcontractor for Geoscience
            Australia, contributing to an initiative that enhanced the
            resolution of GPS and GNSS device positioning. Implemented satellite
            tracking using base-station signal correction data, which was
            published as a backend web service deployed on AWS, utilizing EC2
            instances and Kubernetes for scalability and reliability.
          </p>
        </Entry>

        <Entry
          title="Embedded Engineer"
          leftText="Lode Star"
          rightText="November 2017 - March 2021"
        >
          <p>
            Developed embedded software and hardware interfaces for a prototype
            active sonar system, working with microcontrollers and
            System-on-Chip (SoC) solutions. Implemented signal processing
            algorithms to calculate target position and size. Wrote Linux device
            drivers in C and developed bare-metal firmware for
            STMicrocontrollers. Configured Debian OS and contributed to
            high-level computational code in Python.
          </p>
        </Entry>
      </Heading>
    </WebContent>
  );
}
