import Link from "next/link";
import {
  WebContent,
  Heading,
  NamedList,
  Entry,
} from "@/components/documents/Page";

export default function HomePage() {
  return (
    <WebContent
      name="Multi-Layer Acoustic Model"
      text="Demonstration Web Application by Dr Alexander Cave"
      numPages={1}
      pageNum={1}
    >
      <Heading text="Objective">
        <p>
          The multi-layer web application is a demonstration of{" "}
          <Link
            className="text-blue-700 hover:underline"
            href="/Levesque_Piche_1992.pdf"
          >
            D. Levesque and L. Piche acoustic physics model
          </Link>
          . It models plane wave at some angle of incidence being reflected
          (Rp,Rs) off and traveling through (Tp, Ts) multiple layers of possibly
          resonant material. The coefficients are generated as complex numbers
          representing the amplitude and phase of reflected compression (Rp) and
          reflected shear (Rs) waves as well as transmitted compression (Tp) and
          transmitted shear (Ts) waves.
        </p>
        <p>
          The layers are made of fluids and or solids where the distinction is
          made that a fluid material layer cannot support shear waves. The
          layers are surrounded on either side by possibly dissimilar mediums
          where the first and final layers do not have layer thickness. The
          incident wave can be a compressional or shear wave provided the first
          layer can support a shear wave and this incident wave has both and
          angle of incidence and a frequency. Plots are generated by the web
          application where either the incident wave frequency or angle is swept
          and defines the x-axis of the figures.
        </p>
        <p>
          The material properties as defined through data specifying the
          density, compressional wave speed (m/s) and attenuation (db/m) or the
          compressional modulus as well as for solids the shear wave speed (m/s)
          and attenuation (db/m) or the shear modulus. The models are defined
          through specifying the materials of the first, finial and intermediate
          layers. Where the intermediate layers further defined through layer
          thickness.
        </p>
      </Heading>
    </WebContent>
  );
}
